### ISSUE TITLE
Roles de usuario

### ISSUE THREAD

**Issue by FedeG** [GNUtn/eventoL#125]
Generar roles de un usuario para un respectivo evento y/o sede.
Ejemplo:
 - instalador
 - colaborador
 - asistente

**Comment by reyiyo** [comment]
Administrador = Persona que creó el evento y le puede dar permisos de admin a otros. Puede hacer todo lo que tengan que hacer en un evento
Colaborador = Un tipo de asistente. Por default no tiene permisos especiales. Se les pueden agregar permisos por modelo como en el admin de django y además se van a usar permisos a nivel middleware que filtren las queries (buscar el nombre de eso).
Instalador = Un tipo de colaborador. Puede cargar instalaciones por default.

**Comment by reyiyo** [comment]
Están los modelos y falta ver el tema de permisos. Administrador se llama Organizer

**Comment by reyiyo** [comment]
5270b5af54fc7c289ee9daaa96d4a505ae7f8852 -> add registration staff
a6c2cb0f47c8e823c7877af93c16d393b5c4ec07 -> add organizers

**Comment by reyiyo** [comment]
Finished in 9b826b20004fd624622366cba19ff6efd90b8c41
