### ISSUE TITLE
Probar y modificar templates para el nuevo modelo

### ISSUE THREAD

**Issue by FedeG** [GNUtn/eventoL#133]
- [x] ./manager/templates/registration/collaborator-registration.html
- [x] ./manager/templates/registration/closed-registration.html
- [x] ./manager/templates/registration/password_reset/complete.html
- [x] ./manager/templates/registration/password_reset/reset.html
- [x] ./manager/templates/registration/password_reset/confirm.html
- [x] ./manager/templates/registration/password_reset/done.html
- [x] ./manager/templates/registration/password_reset/confirm_form.html
- [x] ./manager/templates/registration/password_reset/confirm_error.html
- [x] ./manager/templates/registration/attendee-registration.html
- [x] ./manager/templates/registration/installer-registration.html
- [x] ./manager/templates/registration/login.html
- [x] ./manager/templates/registration/become_installer.html
- [x] ./manager/templates/registration/attendee/by-collaborator.html
- [x] ./manager/templates/registration/attendee/search.html
- [x] ./manager/templates/talks/proposal.html
- [x] ./manager/templates/talks/upload_presentation.html
- [x] ./manager/templates/talks/proposal/votes.html
- [x] ./manager/templates/talks/proposal/image-cropping.html
- [x] ./manager/templates/talks/to_talk_form.html
- [x] ./manager/templates/talks/comments.html
- [ ] ./manager/templates/talks/schedule.html
- [x] ./manager/templates/talks/talks_home.html
- [x] ./manager/templates/talks/detail.html
- [ ] ./manager/templates/reports/dashboard.html
- [x] ./manager/templates/contact-message.html
- [x] ./manager/templates/FAQ.html
- [x] ./manager/templates/generic-bootstrap-multiple-model-form.html
- [x] ./manager/templates/installation/installation-form.html
- [x] ./manager/templates/homepage.html
- [x] ./manager/templates/generic-bootstrap-model-form.html
- [x] ./manager/templates/index.html
- [x] ./manager/templates/event/info.html
- [x] ./manager/templates/form_field.html
- [x] ./manager/templates/base.html
- [x] ./manager/templates/base-main.htm

**Comment by reyiyo** [comment]
Cierro este issue, ya que los ítems que faltan los sacamos a issues independientes para tener un mejor control
