### ISSUE TITLE
Probar y modificar vistas para el nuevo modelo

### ISSUE THREAD

**Issue by FedeG** [GNUtn/eventoL#134]
- [x] event_django_view
- [x] index
- [x] event_view
- [x] event
- [x] home
- [x] talk_registration
- [x] room_available
- [x] become_installer
- [x] installation
- [x] confirm_registration
- [x] talk_proposal
- [x] image_cropping
- [x] schedule
- [x] talks
- [x] talk_detail
- [x] talk_delete
- [x] proposal_detail
- [x] upload_presentation
- [x] attendee_search
- [x] attendee_registration_by_collaborator
- [x] contact
- [x] delete_comment
- [x] add_comment
- [x] vote_proposal
- [x] cancel_vote
- [x] confirm_schedule
- [ ] reports
- [x] generic_registration
- [x] registration
- [x] installer_registration
- [x] collaborator_registration

**Comment by reyiyo** [comment]
Cierro este issue, ya que los ítems que faltan los sacamos a issues independientes para tener un mejor control
