### ISSUE TITLE
Probar y modificar forms para el nuevo modelo

### ISSUE THREAD

**Issue by FedeG** [GNUtn/eventoL#135]
- [x] AttendeeSearchForm
- [x] RegistrationForm
- [x] AttendeeRegistrationByCollaboratorForm
- [x] InstallationForm
- [x] HardwareForm
- [x] CollaboratorRegistrationForm
- [x] EventoLUserRegistrationForm
- [x] AttendeeRegistrationForm
- [x] InstallerRegistrationForm
- [x] InstallerRegistrationFromCollaboratorForm
- [x] UserRegistrationForm
- [x] TalkProposalForm
- [x] TalkProposalImageCroppingForm
- [x] TalkForm
- [x] PresentationForm
- [x] ContactMessageForm
- [x] CommentForm

**Comment by ChmlGr** [comment]
Closed for now
