### ISSUE TITLE
Permisos para tomar asistencia

### ISSUE THREAD

**Issue by reyiyo** [GNUtn/eventoL#143]
Que el Organizer pueda asignar a un Collaborator un permiso para tomar asistencia, de modo que los usuarios con ese permiso pueden marcar a alguien como "presente" y además cargar un NonRegisteredAttendee

**Comment by ChmlGr** [comment]
Ahora mismo esto se define con el permiso de usuario django 'Add Attendee'

**Comment by reyiyo** [comment]
implemented in 5270b5af54fc7c289ee9daaa96d4a505ae7f8852
