### ISSUE TITLE
En el formulario de login se superponen el label y el placeholder

### ISSUE THREAD

**Issue by reyiyo** [GNUtn/eventoL#167]
Cuando hago click en Iniciar Sesión, el texto " Nombre de usuario o correo electrónico *" aparece superpuesto con el text field. Luego de hacerle click por ejemplo al fondo blanco el problema se arregla. Imagino que debe ser algo de CSS quizá.

**Comment by reyiyo** [comment]
Sucede cuando se guardan los datos de usuario y password en el navegador. Se ven los datos del navegador guardados y los labels por encima

**Comment by taulamet** [comment]
Verificado! Muchas gracias :)
