### ISSUE TITLE
AttributeError at /admin/manager/nonregisteredattendee/

### ISSUE THREAD

**Issue by ChmlGr** [GNUtn/eventoL#207]
File "/home/chmlgr/Flisol/eventol/eventoL/manager/admin.py", line 41, in filter_event
    if EventUser.objects.get(nonregisteredattendee=attendee, event=event).exists():
AttributeError: 'EventUser' object has no attribute 'exists'

**Comment by FedeG** [comment]
Ya lo cambio para que ande
