### ISSUE TITLE
cuando se pide una charla de un evento que no existe, da error 500

### ISSUE THREAD

**Issue by ChmlGr** [GNUtn/eventoL#214]
ERROR Internal Server Error: /event/Formosa/talk/detail/proposal/20/
[Wed Apr 20 05:30:54 2016] [error] Traceback (most recent call last):
[Wed Apr 20 05:30:54 2016] [error] File "/var/lib/openshift/56ff778889f5cf28760001da/python/virtenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
[Wed Apr 20 05:30:54 2016] [error] response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Apr 20 05:30:54 2016] [error] File "/var/lib/openshift/56ff778889f5cf28760001da/python/virtenv/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
[Wed Apr 20 05:30:54 2016] [error] return wrapped(*args, **kwargs)
[Wed Apr 20 05:30:54 2016] [error] File "/var/lib/openshift/56ff778889f5cf28760001da/app-root/runtime/repo/manager/views.py", line 459, in proposal_detail
[Wed Apr 20 05:30:54 2016] [error] return render(request, 'activities/talks/detail.html', update_event_info(event_slug, render_dict))
[Wed Apr 20 05:30:54 2016] [error] File "/var/lib/openshift/56ff778889f5cf28760001da/app-root/runtime/repo/manager/views.py", line 44, in update_event_info
[Wed Apr 20 05:30:54 2016] [error] event = event or Event.objects.get(slug__iexact=event_slug)
[Wed Apr 20 05:30:54 2016] [error] File "/var/lib/openshift/56ff778889f5cf28760001da/python/virtenv/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
[Wed Apr 20 05:30:54 2016] [error] return getattr(self.get_queryset(), name)(*args, **kwargs)
[Wed Apr 20 05:30:54 2016] [error] File "/var/lib/openshift/56ff778889f5cf28760001da/python/virtenv/lib/python2.7/site-packages/django/db/models/query.py", line 357, in get
[Wed Apr 20 05:30:54 2016] [error] self.model._meta.object_name)
[Wed Apr 20 05:30:54 2016] [error] DoesNotExist: Event matching query does not exist.

**Comment by FedeG** [comment]
- [ ] manager/security.py:18:    content_type = ContentType.objects.get_for_model(NonRegisteredAttendee)
- [ ] manager/security.py:19:  user.user_permissions.add(Permission.objects.get(content_type=content_type, codename='add_nonregisteredattendee'))
- [ ] manager/security.py:21:        Permission.objects.get(content_type=content_type, codename='change_nonregisteredattendee'))
- [ ] manager/security.py:23:    content_type = ContentType.objects.get_for_model(EventUser)
- [ ] manager/security.py:28:        attendance_permission = Permission.objects.get(codename='can_take_attendance', name='Can Take Attendance',
- [ ] manager/security.py:36:    user.user_permissions.add(Permission.objects.get(content_type=content_type, codename='change_eventuser'))
- [ ] manager/security.py:54:            organizers.permissions.add(Permission.objects.get(codename=perm))
- [ ] manager/security.py:58:        organizers = Group.objects.get(name__iexact='Organizers')
- [ ] manager/security.py:78:            reporters.permissions.add(Permission.objects.get(codename=perm))
- [ ] manager/security.py:82:        reporters = Group.objects.get(name__iexact='Reporters')
- [ ] manager/views.py:44:    event = event or Event.objects.get(slug__iexact=event_slug)
- [ ] manager/views.py:140:        event = Event.objects.get(slug__iexact=event_slug)
- [ ] manager/views.py:187:    event = Event.objects.get(slug__iexact=event_slug)
- [ ] manager/views.py:195:    proposal = TalkProposal.objects.get(pk=pk)
- [ ] manager/views.py:205:                activity.room = Room.objects.get(pk=request.POST.get('room', None))
- [ ] manager/views.py:223:    vote = Vote.objects.get_for_user(proposal, request.user)
- [ ] manager/views.py:224:    score = Vote.objects.get_score(proposal)
- [ ] manager/views.py:249:                event = Event.objects.get(slug__iexact=event_slug)
- [ ] manager/views.py:287:    event = Event.objects.get(slug__iexact=event_slug)
- [ ] manager/views.py:299:        proposal = TalkProposal.objects.get(pk=pk)
- [ ] manager/views.py:332:    event = Event.objects.get(slug__iexact=event_slug)
- [ ] manager/views.py:337:    activity = Activity.objects.get(pk=pk) if pk else Activity(event=event)
- [ ] manager/views.py:350:                activity.room = Room.objects.get(pk=request.POST.get('room', None))
- [ ] manager/views.py:390:    event = Event.objects.get(slug__iexact=event_slug)
- [ ] manager/views.py:410:    event = Event.objects.get(slug__iexact=event_slug)
- [ ] manager/views.py:430:    proposal = TalkProposal.objects.get(activity__pk=pk)
- [ ] manager/views.py:439:    talk = TalkProposal.objects.get(pk=pk)
- [ ] manager/views.py:447:    proposal = TalkProposal.objects.get(pk=pk)
- [ ] manager/views.py:450:    vote = Vote.objects.get_for_user(proposal, request.user)
- [ ] manager/views.py:451:    score = Vote.objects.get_score(proposal)
- [ ] manager/views.py:506:        eventUser = EventUser.objects.get(pk=pk)
- [ ] manager/views.py:552:                Collaborator.objects.get_or_create(eventUser=event_user)
- [ ] manager/views.py:561:        permission = Permission.objects.get(codename='can_take_attendance')
- [ ] manager/views.py:575:    event = Event.objects.get(slug__iexact=event_slug)
- [ ] manager/views.py:607:    event = Event.objects.get(slug__iexact=event_slug)
- [ ] manager/views.py:624:            contact_message.event = Event.objects.get(slug__iexact=event_slug)
- [ ] manager/views.py:639:        Comment.objects.get(pk=comment_pk).delete()
- [ ] manager/views.py:646:    comment = Comment(activity=TalkProposal.objects.get(pk=pk).activity, user=request.user)
- [ ] manager/views.py:656:    proposal = TalkProposal.objects.get(pk=pk)
- [ ] manager/views.py:657:    exits_vote = Vote.objects.get_for_user(proposal, request.user)
- [ ] manager/views.py:665:    proposal = TalkProposal.objects.get(pk=pk)
- [ ] manager/views.py:666:    vote = Vote.objects.get_for_user(proposal, request.user)
- [ ] manager/views.py:675:    event = Event.objects.get(slug__iexact=event_slug)
- [ ] manager/views.py:684:    event = Event.objects.get(slug__iexact=event_slug)
- [ ] manager/views.py:719:        (votes, lambda vote: TalkProposal.objects.get(pk=vote.object_id, activity__event=event).activity.title,
- [ ] manager/views.py:731:    event = Event.objects.get(slug__iexact=event_slug)
- [ ] manager/views.py:865:    event = Event.objects.get(slug__iexact=event_slug)
- [ ] manager/views.py:904:    room = Room.objects.get(pk=pk)
- [ ] manager/views.py:920:        room = Room.objects.get(pk=pk)
- [ ] manager/views.py:928:                room.event = Event.objects.get(slug__iexact=event_slug)
