### ISSUE TITLE
Actualización de paquetes de pip

### ISSUE THREAD

**Issue by FedeG** [GNUtn/eventoL#80]
Hay paquetes sin actualizar

**Comment by FedeG** [comment]
Hay 5 paquetes que están sin actualizar.

**Comment by FedeG** [comment]
No tiene problemas de seguridad o errores graves, solo están desactialozados

**Comment by reyiyo** [comment]
- django 1.8 va a ser una migración dolorosa :P así que queda para el año que viene
- django-image-cropping lo tuve que downgradear hoy, porque no andaba en el admin
- django-tables2 no se usa... hay que ver cómo hacés lo del cronograma y si no lo usás, lo podés sacar

Con el resto no creo que haya problemas

**Comment by FedeG** [comment]
Cierro esta issue porque se va a convertir en issues para eventoL 2.0
