### ISSUE TITLE
No se puede editar un lugar que acabamos de crear

### ISSUE THREAD

**Issue by mauriciopasquier** [GNUtn/eventoL#81]
Me registré como colaborador en Merlo y tenía disponible la UTN de Paraná (?) en "buildings". Estaba configurada en la sede (`place`). Agregué un lugar nuevo (Hacklab Oeste) así cambiaba el lugar de la sede, pero puse Save and continue editing.. al no tener el nuevo lugar disponible me tiró error de permisos.

Cuando cambié el `place` en la sede ya pude editar, todo bien... Es un poco confuso nomás :P

**Comment by reyiyo** [comment]
Hola @mauriciopasquier!

Es verdad... eso hoy en día no se está usando. Es una idea que teníamos para hacer, pero no llegamos a terminarla y quedó ahí para el futuro. Lo mimso con el #82. Dejo los issues abiertos para cuando lo implementemos.

Gracias por el reporte!

**Comment by mauriciopasquier** [comment]
Ah, no hay drama. Estoy probando todo.. está muy buena la aplicación!

**Comment by reyiyo** [comment]
Con el commit referenciado, se cierra este issue, ya que la forma de crear el lugar cambió y se puede editar.
