### ISSUE TITLE
URL inválida para Contacto de tipo Email y Lista de correo

### ISSUE THREAD

**Issue by mauriciopasquier** [GNUtn/eventoL#83]
No puedo poner un mail como URL, dice que es inválida. Tampoco con `mailto:<mail>`

**Comment by reyiyo** [comment]
En qué parte?

**Comment by mauriciopasquier** [comment]
Al intentar cargar un nuevo Contacto

**Comment by reyiyo** [comment]
Por default, todas las sedes tienen un contacto por mail, que es la dirección de mail que se configura en la sede. Los usuarios ingresan el mensaje a través de un formulario y se manda por mail a ese que está configurado en la sede.

Necesitás agregar otro?

**Comment by mauriciopasquier** [comment]
No, con ese basta (que probé y anda joya), pero como está la opción de agregar mails (y listas de correo) pensé en usarla :P 

Tampoco me deja poner urls vacías (o sea no poner una)

**Comment by reyiyo** [comment]
Claro, el problema con las listas de correo, es que a la mayoría no podés mandar un mail directamente, sino que la persona tiene que estar suscripta. Nostotros en caba, ponemos el link a la página de mailman para que se registren a la lista

**Comment by mauriciopasquier** [comment]
Claro, al final hice algo así. Entonces el problema que queda es que un contacto de tipo Email no funciona y ya está resuelto con el contacto por sede.. yo sacaría ese tipo. Es un tema de datos, en vez de funcionalidad, no? Otra es aceptar URIs mailto, pero a quién le gustan esas :P
